In [1]:
import pandas as pd

# Load the CSV file
file_path = "./fruits.csv"
df = pd.read_csv(file_path)

# Display the first few rows to understand its structure
df.head()

,name,energy (kcal/kJ),water (g),protein (g),total fat (g),carbohydrates (g),fiber (g),sugars (g),calcium (mg),iron (mg),...,potassium (mg),sodium (g),vitamin A (IU),vitamin C (mg),vitamin B1 (mg),vitamin B2 (mg),viatmin B3 (mg),vitamin B5 (mg),vitamin B6 (mg),vitamin E (mg)
0,Apple nutrition facts,48/200,86.70,0.27,0.13,12.70,1.3,10.1,5,0.07,...,90,0,38,4.0,0.019,0.028,0.091,0.071,0.037,0.05
1,Apricot nutrition facts,48/201,86.40,1.40,0.39,11.12,2,9.24,13,0.39,...,259,1,1926,10.0,0.03,0.04,0.6,0.24,0.054,0.89
2,Avocado nutrition,160/670,73.23,2.00,14.70,8.53,6.7,0.66,12,0.55,...,485,7,146,10.0,0.067,0.13,1.738,1.389,0.257,2.07
3,Banana nutrition facts,89/371,74.91,1.09,0.33,22.84,2.6,12.23,5,0.26,...,358,1,64,8.7,0.031,0.073,0.665,0.334,0.367,0.1
4,Blackberries nutrition,43/181,88.15,1.39,0.49,9.61,5.3,4.88,29,0.62,...,162,1,214,21.0,0.02,0.026,0.646,0.276,0.03,1.17

In [2]:
# Select relevant numerical columns for training
df_cleaned = df[['carbohydrates (g)', 'fiber (g)', 'sugars (g)', 'water (g)', 'protein (g)', 'total fat (g)']]

# Convert non-numeric values to numeric, forcing errors to NaN for cleaning
df_cleaned = df_cleaned.apply(pd.to_numeric, errors='coerce')

# Drop rows with missing values
df_cleaned = df_cleaned.dropna()

# Display summary statistics to check data consistency
df_cleaned.describe()

,carbohydrates (g),fiber (g),sugars (g),water (g),protein (g),total fat (g)
count,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000
mean,15.693636,2.931818,11.469318,82.009091,1.070909,0.659318
std,13.677661,2.202512,12.300846,14.269760,0.546063,2.179533
min,6.580000,0.400000,0.660000,20.530000,0.270000,0.100000
25%,9.807500,1.575000,7.205000,81.495000,0.700000,0.150000
50%,12.450000,2.000000,9.210000,85.875000,0.880000,0.290000
75%,15.927500,3.325000,11.035000,88.082500,1.392500,0.402500
max,75.030000,10.400000,66.470000,91.850000,2.550000,14.700000

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

# Define features (X) and target (y)
X = df_cleaned[['carbohydrates (g)', 'fiber (g)', 'water (g)', 'protein (g)', 'total fat (g)']]
y = df_cleaned['sugars (g)']

# Split into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train a Linear Regression model
model = LinearRegression()
model.fit(X_train_scaled, y_train)

# Predict on the test set
y_pred = model.predict(X_test_scaled)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

mae, r2

(0.8666127599348594, 0.9950732930803438)

In [ ]:
/home/arshlaan/Downloads/Frutly/runs/detect/train11/weights/best.pt

In [ ]:
yolo detect train data=dataset.yaml model=/home/arshlaan/Downloads/Frutly/runs/detect/train11/weights/best.pt epochs=10 imgsz=640